name: Detect Pull Request Review

on:
  pull_request_review:
    types:
      - submitted

jobs:
  detect-review:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Check Review State
        uses: actions/github-script@v7
        with:
          script: |
            const reviewState = context.payload.review.state;
            const prNumber = context.payload.pull_request.number;

            if (reviewState === 'approved') {
              console.log(`PR #${prNumber} was approved.`);
              core.setOutput('trigger_update', 'true');
            } else {
              console.log(`Review state is ${reviewState}, skipping.`);
              core.setOutput('trigger_update', 'false');
            }
        id: check-review

      - name: Trigger Follow-Up Workflow
        if: steps.check-review.outputs.trigger_update == 'true'
        run: |
          echo "Triggering follow-up action for PR approval."
