name: Detect Pull Request Review and Trigger Workflow

on:
  pull_request_review:
    types:
      - submitted

jobs:
  trigger-label-update:
    runs-on: ubuntu-latest

    permissions:
      actions: write # Required to trigger workflows
      pull-requests: read

    steps:
      - name: Trigger Label Update Workflow
        if: ${{ github.event.review.state == 'approved' }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const prNumber = context.payload.pull_request.number;

            console.log(`Triggering label update workflow for PR #${prNumber}.`);

            await github.rest.actions.createWorkflowDispatch({
              owner,
              repo,
              workflow_id: "update-labels.yml", // Replace with the actual workflow filename
              ref: "main", // Default branch where the second workflow is defined
              inputs: { pr_number: prNumber.toString() },
            });
