name: Detect Pull Request Review

on:
  pull_request_review:
    types:
      - submitted

jobs:
  add-approval-comment:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      issues: write

    steps:
      - name: Add Approval Comment
        if: ${{ github.event.review.state == 'approved' }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const issue_number = context.payload.pull_request.number;

            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number,
              body: "PR approved: Please update labels.",
            });
            console.log(`Comment added for PR #${issue_number}`);
