name: Update Labels After Approval

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: "Pull Request Number"
        required: true

jobs:
  update-labels:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      issues: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Remove and Add Labels
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const issue_number = parseInt(inputs.pr_number);

            const labelsToRemove = ['waiting-review', 'ready to review'];
            const labelsToAdd = ['approved', 'auto merge'];

            console.log(`Processing PR #${issue_number} in ${owner}/${repo}.`);

            const { data: labels } = await github.rest.issues.listLabelsOnIssue({
              owner,
              repo,
              issue_number,
            });

            for (const label of labelsToRemove) {
              if (labels.some(l => l.name === label)) {
                await github.rest.issues.removeLabel({
                  owner,
                  repo,
                  issue_number,
                  name: label,
                });
                console.log(`Removed label: ${label}`);
              }
            }

            await github.rest.issues.addLabels({
              owner,
              repo,
              issue_number,
              labels: labelsToAdd,
            });
            console.log(`Added labels: ${labelsToAdd.join(', ')}`);
